// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bpf_logger")
	ScopeName = "github.com/alexandreLamarre/otelcol-bpf/extension/bpflogger"
)

const (
	ExtensionStability = component.StabilityLevelAlpha
)
