receivers:
  bpfstack:
  pprofreceiver:
    endpoints:
      - id : example-server
        extra_labels:
          foo : bar
        endpoint: "http://localhost:6060"
        targets:
          profile:
          block:
          mutex:
          goroutine:
          heap:
          threadcreate:
          allocs:
processors:
  batch:
exporters:
  otlp/debug:
    endpoint : 127.0.0.1:4317
    compression: none
    tls:
      insecure: true
  otlphttp/debug:
    endpoint : http://127.0.0.1:4318
    compression: none
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200
  otlp/pprofserver:
    endpoint: 127.0.0.1:10001
    compression: none
    tls:
      insecure: true
extensions:
  pprof:
  healthcheckv2:
service:
  extensions: [healthcheckv2, pprof]
  pipelines:
    # traces:
    #   receivers: [bpfstack]
    #   processors: [batch]
    #   exporters: [otlp/debug]
    logs:
      receivers: [bpfstack, pprofreceiver]
      processors: [batch]
      exporters: [otlp/pprofserver]
    # metrics:
    #   receivers: [bpfstack]
    #   processors: [batch]
    #   exporters: [debug]
    # logs:
    #   receivers: [bpfstack]
    #   processors: [batch]
    #   exporters: [debug]