// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("bpftcp")
	ScopeName = "github.com/alexandreLamarre/otelcol-bpf/receiver/bpftcp"
)

const (
	MetricsStability = component.StabilityLevelAlpha
)
