// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("pprofreceiver")
	ScopeName = "github.com/alexandreLamarre/otelbpf/receiver/pprofreceiver"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
