name : Validate

permissions:
  contents : read

on:
  pull_request:
    paths-ignore:
      - "docs/**"
      - "*.md"
      - ".gitignore"
      - "CODEOWNERS"
      - "LICENSE"
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses : actions/setup-go@v5
        with:
          go-version: ">=1.23.0"
      - name : Setup LLVM dependencies
        run : |
          sudo apt-get install clang-11 llvm-11
      - name : Install mdatagen
        run: |
          git clone --depth 1 --branch v0.118.0 https://github.com/open-telemetry/opentelemetry-collector /tmp/opentelemetry-collector
          cd /tmp/opentelemetry-collector/cmd/mdatagen && go install .
      - name : Run go mod tidy
        run : make gotidy
      - name : Run generate targets
        run : make gogenerate
      - name : Generate BPF headers
        run : make get-headers
      - name : Validate repo
        run : git diff --exit-code
